FROM eclipse-temurin:17-jre-focal

WORKDIR /app

RUN apt-get update && apt-get install -y curl

ENV LAVALINK_VERSION=4.0.7

RUN curl -L https://github.com/lavalink-devs/Lavalink/releases/download/${LAVALINK_VERSION}/Lavalink.jar -o Lavalink.jar

COPY application.yml .

EXPOSE 2333

CMD ["java", "-Xmx512m", "-jar", "Lavalink.jar"]